spring:
  profiles:
    active:
      - dog
      - EN
      - qa

---
spring:
  profiles: dev
guru:
  username: YmlUserName-Dev
  password: YmlPassword-Dev
  jdbcUrl: YmlUrl-Dev

---
spring:
  profiles: qa
guru:
  username: YmlUserName-QA
  password: YmlPassword-QA
  jdbcUrl: YmlUrl-QA